### ISSUE TITLE
"Release" Checklist

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#188]
- [ ] Make sure code is linted and blacked.
- [ ] Make sure all tests pass.
- [ ] Put updates in changelog.
- [ ] Tag release 1.0.0, merge into main.
- [ ] Update docs.
- [ ] Make sure the documentation build looks good.
- [ ] Test UI status.
- [ ] Send email to:
    - [ ] People on waitlist.
    - [ ] Current users.
- [ ] Ask people to like and star the repo.
- [ ] Make some posts (LinkedIn, twitter) ?

Missing anything?
