### ISSUE TITLE
tidy3d improvements for gdsfactory plugin and other PIC workflows

### ISSUE THREAD

**Issue by joamatab** [flexcompute/tidy3d#217]
Hi Tyler and Momchil,

I've been working on a [gdsfactory plugin](https://gdsfactory.github.io/gdsfactory/notebooks/plugins/tidy3d/00_tidy3d.html/)

I have a few questions

- [x] How can we calculate the Sparameters at more than 1 wavelength?  `gdsfactory/simulation/gtidy3d/get_results.py` [see issue](https://github.com/gdsfactory/gdsfactory/issues/192)
- [x] How can get the right plot_modes? [see issue](https://github.com/gdsfactory/gdsfactory/issues/191)
- [x] how can we use dispersive materials? [see issue](https://github.com/gdsfactory/gdsfactory/issues/193)

Here are a few improvement suggestions:

- [ ] add index plot to Simulation (more intuitive than epsilon) `simpluation.plot_index()`
- [ ] add material index legend to Simulation.plot() so we know each material index.
- [ ] implement sidewall angle in `from_gds`
- [ ] implement cache so simulations previously computed to not need to run again (you can take a look at `gdsfactory/simulation/gtidy3d/get_results.py`)

**Comment by tylerflex** [comment]
Thanks Joquin,
I commended on the issues associated with the first 3 questions.
I think the other 4 suggestions are interesting, but I dont think we have the bandwidth to handle these before your demo.  I can work with you to look into the mode solver one though.

**Comment by tylerflex** [comment]
Also, note we have a Discussions tab on this repo so for more general discussions and feedback that could be also a good place to do that.

**Comment by joamatab** [comment]
Awesome Tyler,

thank you for your fast response 

I was able to get

- nice mode solver plots
- Sparameters
- dispersive material plots

See plugin [docs here](https://gdsfactory.github.io/gdsfactory/notebooks/plugins/tidy3d/00_tidy3d.html)
