### ISSUE TITLE
Checklist for 2.0 release

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#718]
Let's keep a running list of things we need to check / refine before 2.0 release.
Feel free to add.

## Docs

- [x] Add FAQ topics from tidy3d issues.
- [x] Remove reference to "beta" version of tidy3d in docs, make "start here" reflect release.
- [x] Add reference to `updated_copy` [here](https://docs.flexcompute.com/projects/tidy3d/en/latest/faq.html#why-can-i-not-change-tidy3d-instances-after-they-are-created)
- [x] Check all notebooks for: #795 
    - [x] No extra output from plotting.
    - [x] toggle verbose in webapi depending on desired output.
    - [x] No noticeable change in results
    - [x] Remove any unnecessary warnings.
    - [x] Ensure notebooksreflect new default BC of PML and PolySlab reference plane of "middle".
    - [x] Correct any weird output.
    - [x] Ensure all written material is up to date.
- [x] Find replace Flex Unit -> Flex Credit anywhere it appears in notebook / docs output. IMPORTANT: not the webapi internals! Those still rely on FlexUnit.
- [x] Run jupyterblack?
- [ ] Build and proofread docs
    - [ ] Fix misformatted docstrings.
    - [ ] Fix any typos.
    - [ ] Review notebooks for formatting errors, eg bullet points not rendering correctly.
- [x] Re-run notebooks?
- [x] Re-run backend tests?
- [ ] Official Release

## Front end (tyler?)

- [x] Fix any typos or misformatted strings in exceptions / logs.
- [x] Make sure the docstrings run correctly. #792 (but double check after all 2.0 PRs merged).
- [x] Remove deprecation warnings. #793 
- [x] Stop uploading to tidy3d-beta, change PIP_NAME to "tidy3d" #794
- [x] import plugins from `tidy3d.plugins.X` instead of directly from `tidy3d.plugins` #787 
- [x] Update main README #794
